version: 2
jobs:
  build:
    working_directory: ~/portfolio
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          RAILS_ENV: test
      - image: circleci/mongo:3.4.16
        environment:
          MONGO_INITDB_DATABASE: portfolio_test
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      # Wait for database
      - run:
          name: Wait for database
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      # Setup the environment variables
      - run:
          name: Setup the environment variables
          command: cp .env.example .env
      # Run automated tests
      - run:
          name: Run automated tests
          command: bundle exec rspec
      # Check code styling using Rubocop
      - run:
          name: Check code styling using Rubocop
          command: bundle exec rubocop
